## Introducción Numpy

Numpy es una de las librerías más importante del stack científico de python. Nos facilita realizar operciones matemáticas mediante la implementación de arreglos y pone a nuestra disposición una srie de rutinas para procesarlos.  

Por convención la manera de importar numpy es la siguiente:  

In [1]:
import numpy as np

Una de las principales aportaciones que nos da numpy es el llamado `ndarray` (Arreglo de N dimensiones), este objero puede almacenar uno o más elementos y ordenarlos en N número de dimensiones. Pudieramos imaginar estos arreglos como vectores o matrices y como veremos más adelante, Numpy nos ofrece distintas formas de trabajar con ellos.

## Creación de arreglos

A pesar de que existe la clase `numpy.ndarray`, esta no es comunmente la manera en que se crea un arreglo. Por lo general, los arreglos se crean con algna de las funciones que facilitan esta tarea. Entre las más comunes están las iguientes:

***np.array()***  
Genera un arreglo a partir de una lista u objeto iterable.

In [2]:
np.array([1, 2, 3, 4, 5])

array([1, 2, 3, 4, 5])

In [3]:
np.array([[1, 2, 3, 4],[ 5, 6, 7, 8]])

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

***np.arange()***  
genera un arreglo con valores enteros correspondientes al rango solicitado.

In [4]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
np.arange(10, 15)

array([10, 11, 12, 13, 14])

En otras ocasiones, nos puede ser util generar un arreglo donde todos sus elementos son ceros o unos. Esto lo podemos lograr con los siguientes métodos:

***np.zeros()***  
Genera un arreglo de las dimensiones especificadas en el cual todos sus elementos son ceros.

In [6]:
np.zeros(shape=(3, 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

***np.ones()***  
Genera un arreglo de las dimensiones especificadas en el cual todos sus elementos son unos.

In [7]:
np.ones(shape=(3, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

***np.eye()***  
Genera un arreglo cuadrado con unos sobre su diagonal y ceros en el resto de las posiciones. Similar a una matriz identidad.

In [8]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

***np.diag()***  
Toma una lista de valores de una lista u objeto iterable y los coloca sobre la diagonal de un arreglo cuadrado llenando las demás posiciones con ceros.

In [9]:
np.diag([1, 2, 3, 4])

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

Además existen algunos otros métodos que pueden llegar a ser muy útiles en cieras ocasiones.

***np.linspace()***  
Genera un arreglo con números separados a intervalos regulares.

In [10]:
np.linspace(1, 2, 5)

array([1.  , 1.25, 1.5 , 1.75, 2.  ])

***np.random***  
Dentro del submodulo `random`, Numpy nos ofrece vrias opciones para crear arreglos con datos aleatorios.

In [11]:
np.random.rand(6, 2)

array([[0.51774099, 0.51619596],
       [0.54040033, 0.15372461],
       [0.99115979, 0.56683524],
       [0.4667341 , 0.40873168],
       [0.68900127, 0.13100146],
       [0.24720834, 0.48935144]])

## Forma de los arreglos

Los arreglos de numpy inluyen el atributo `shape`, este contiene una tupla que nos indica la forma del arreglo.

In [12]:
arreglo = np.array([[1, 2], 
                    [3, 4], 
                    [5, 6]])

arreglo.shape

(3, 2)

La forma de los arreglos tambien puede ser modificada con los siguientes métodos disponibles en Numpy:

***np.ndarray.reshape()***  
Cambia la forma de un arreglo a la forma solicitada.

In [13]:
arreglo = np.arange(10)    # Arreglo de una dimension

arreglo.reshape((5, 2))

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

***np.ndarray.ravel()***  
Convierte un arreglo en uno de una dimensión.

In [14]:
arreglo = np.arange(27).reshape([3,3,3])    # Arreglo de 3 dimensiones

arreglo.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

## Índices y cortes con arreglos

Podemos acceder a los elementos de un arreglo de numpy de manera similar a la que usamos para acceder a los elementos de una lista. Numpy, toma esta funcionalidad de Python y la extiende para hacer más fail el uso en arreglos de N dimensiones permitiendonos inicar un indice para cada una de las dimensiones de un arreglo separando estos por comas.  

Ejemplo:  

Tomando el siguiente arreglo podemos seleccionar el elemento que contiene el número 6 de la siguiente manera

In [15]:
arreglo = np.array([[1, 2, 3],
                    [4, 5, 6]])

arreglo[1, 2]

6

## Cortes

Los cortes siguen la misma lógica. Para hacerlos introducimos un indice o corte para cada una de las dimensiones y los separamos por una coma. El resultado será un arreglo que solo incluye esos elementos.

Ejemplo:
Tomando el siguiente arreglo podemos generar un corte que solo contenga los elementos 2, 3, 5 y 6

In [16]:
arreglo = np.array([[1, 2, 3],
                    [4, 5, 6]])

arreglo[:, 1:]

array([[2, 3],
       [5, 6]])

### np.newaxis

En algunas ocasiones solo requerimos agregar una dimensión a un arreglo existente. En esos casos podemos usar `np.newaxis` como indice en uno de los ejes para realizarlo.  

Ejemplo:

In [17]:
arreglo = np.arange(5)

arreglo

array([0, 1, 2, 3, 4])

In [18]:
arreglo[:,np.newaxis]

array([[0],
       [1],
       [2],
       [3],
       [4]])

Esto seria el equivalente usando reshape:

In [19]:
arreglo.reshape(5,1)

array([[0],
       [1],
       [2],
       [3],
       [4]])

## Operaciones con arreglos

En general, cuando aplicamos operacciones matemáticas con Numpy, estas se aplican a cada uno de los elementos.

Por ejemplo, al sumar una constante (escalar) a un arreglo, la operación se realiza para cada uno de los elementos.

In [20]:
np.array([1, 2, 3]) + 10

array([11, 12, 13])

In [21]:
np.array([1, 2, 3]) ** 2

array([1, 4, 9])

Al aplicarlas entre dos arreglos, estas se aplican a cada uno de los elementos con el elemento correspondiente de el otro arreglo.

In [22]:
np.array([1, 2, 3]) * np.array([1, 10, 100])

array([  1,  20, 300])

In [23]:
np.array([1, 2, 3]) / np.array([2, 4, 8])

array([0.5  , 0.5  , 0.375])

Además podemos aplicar comparaciones lógicas.

In [24]:
np.array([1, 2, 3]) > 2

array([False, False,  True])

In [25]:
np.array([1, 2, 3]) == 2

array([False,  True, False])

## Broadcasting

Uno de los requerimientos para poder realizar operaciones entre dos arreglos es que estos tengan las mismas dimensiones. De no ser así, Numpy arroja un mensaje de error indicando que no es posible realizar la operación.

Existe un caso especial en el que si podemos aplicar operaciones entre dos arreglos de distinta forma, pero requerimos que por lo menos el tamaño de una de las dimensiones coincida con la del otro arreglo y el tamaño del resto sea 1. En este caso, Numpy replica el contenido en el arreglo más chico N numero de veces para igualar la forma del arreglo más grande y poder realizar la operación. A esto se le conoce como Broadcasting.  

![Broadcasting](img/broadcasting.png)  

Ejemplo:

In [26]:
numeros = np.arange(1,11)

numeros * numeros[:,np.newaxis]

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [  2,   4,   6,   8,  10,  12,  14,  16,  18,  20],
       [  3,   6,   9,  12,  15,  18,  21,  24,  27,  30],
       [  4,   8,  12,  16,  20,  24,  28,  32,  36,  40],
       [  5,  10,  15,  20,  25,  30,  35,  40,  45,  50],
       [  6,  12,  18,  24,  30,  36,  42,  48,  54,  60],
       [  7,  14,  21,  28,  35,  42,  49,  56,  63,  70],
       [  8,  16,  24,  32,  40,  48,  56,  64,  72,  80],
       [  9,  18,  27,  36,  45,  54,  63,  72,  81,  90],
       [ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100]])

## Arreglos vs matrices

Además del arreglo de N dimensiones, Numpy incluye matrices como estructura de datos. Estas se comportan de la manera que esperaríamos en algebra lineal.

Las matrices se pueden generar usando `np.matrix()`.

In [27]:
matriz = np.matrix([[1, 2], 
                    [3, 4]]) 

matriz * matriz

matrix([[ 7, 10],
        [15, 22]])

A pesar de esto, la misma documentación de Numpy recomienda no usar esta clase para realizar este tipo de operaciones ya que esta pudiera ser retirada en el futuro. En su lugar nos recomienda realizar las operaciones usando arreglos.

Para realizar esta misa operación con arreglos usamos:

In [28]:
arreglo = np.array([[1, 2], 
                    [3, 4]]) 

arreglo.dot(arreglo)

array([[ 7, 10],
       [15, 22]])

## Reducciones

En numpy existen varios métodos que nos permiten agregar o reducir la información contenida en algun arreglo. entre los más comunes se encuentran:  
* `np.sum()`  
* `np.mean()`  
* `np.min()`  
* `np.max()`  

Todos ellos parten de un arreglo y aplican distintos procedimientos para llegar a una respuesta. Por defecto, Numpy aplica estos métodos en la totalidad del arreglo, pero usando el argumento `axis` podemos controlar la forma en que se aplican.  

Los valores que acepta este argumento son los siguientes:

![Ejemplos de uso de axis](img/numpy_axis.png)

In [29]:
arreglo = np.array([[ 1,   2],
                   [ 10,  20],
                   [100, 200]])

In [30]:
arreglo.sum()

333

In [31]:
arreglo.sum(axis=0)

array([111, 222])

In [32]:
arreglo.sum(axis=1)

array([  3,  30, 300])