## Introducción Numpy

In [ ]:
import numpy as np

## Creación de arreglos

Crea un arreglo de una dimensión con los siguientes valores: 8, 4, 6, 8, 1, 2

Crea un arreglo con los números del 0 al 10.

Crea un arreglo con 11 elementos con los números distribuidos en intervalos regulares del 0 al 1 

Usando los métodos dentro de `np.random` crea un arreglo con números al azar de dimensiones 3x3.

Crea un arreglo de 3x3 con valores de punto flotante aleatorios entre 10 y 20.

## Forma de los arreglos

¿Cuál es la forma del siguiente arreglo?

In [ ]:
arreglo = np.array([[1,2,3],[4,5,6]])

Crea un arreglo de 10x10 con los números del 0 al 99.

Cambia la forma del siguiente arreglo y conviertelo en uno de una dimensión.

In [ ]:
arreglo = np.array([[1,2,3],[4,5,6]])

## Índices y cortes con arreglos

Usando el siguiente arreglo genera las siguentes salidas usando un solo indice/corte para cada una.

In [ ]:
numeros = np.arange(100).reshape((10,10))
numeros

Usando indices selecciona el elemento "42" dentro del arreglo `prueba`.

Usando un solo corte, selecciona toda la primera fila.  
```python
array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
```

Genera un corte con la última columna.  
```python
array([ 9, 19, 29, 39, 49, 59, 69, 79, 89, 99])
```

Genera el siguiente corte:

```python
array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24]])
```

Genera el siguiente corte:

```python
array([0, 3, 6, 9])
```

Genera el siguiente corte:

```python
array([[99, 98, 97, 96, 95, 94, 93, 92, 91, 90],
       [89, 88, 87, 86, 85, 84, 83, 82, 81, 80],
       [79, 78, 77, 76, 75, 74, 73, 72, 71, 70],
       [69, 68, 67, 66, 65, 64, 63, 62, 61, 60],
       [59, 58, 57, 56, 55, 54, 53, 52, 51, 50],
       [49, 48, 47, 46, 45, 44, 43, 42, 41, 40],
       [39, 38, 37, 36, 35, 34, 33, 32, 31, 30],
       [29, 28, 27, 26, 25, 24, 23, 22, 21, 20],
       [19, 18, 17, 16, 15, 14, 13, 12, 11, 10],
       [ 9,  8,  7,  6,  5,  4,  3,  2,  1,  0]])
```

## Operaciones con arreglos

Usando los siguientes arreglos realiza las siguientes operaciones.

In [ ]:
A = np.array([[1, 2, 8], 
              [5, 8, 1], 
              [9, 7, 0]])

B = np.array([[5, 7, 6], 
              [7, 3, 1],
              [2, 8, 6]])

Suma `A` + 10

Multiplica `B` por 3

Suma `A` más `B`

Multiplica la primer columna de `A` por 1, la segunda por 10 y la tercera por 100. 

Multiplica la primer fila de `A` por 1, la segunda por 10 y la tercera por 100.

## Arreglos vs matrices

Multiplica los elemento de `A` por los correpondientes de `B`

Calcula el producto punto de `A` punto `B`

## Reducciones

Usando el arreglo `valores` contesta los siguientes ejercicios

In [ ]:
valores = np.array([[4, 2, 1, 3], 
                    [5, 6, 8, 7]])

Obten el valor máximo del arreglo.

Obten la suma de cada columna.

Obten el promedio de cada fila.